General:
  Verbosity: "NONE"
  CosineZIgnored: true
  CalculationType: "Binned"

OscProbCalcer:
  - Config: "Prob3ppLinear:./build/Linux/configs/OscProbCalcerConfigs/Prob3ppLinear.yaml"

Binned:
  FileName: "FileName.root"
  EnergyAxisHistName: "EnergyAxis"
  CosineZAxisHistName: "CosineZAxis"
