General:
  Verbosity: "NONE"
  CosineZIgnored: true
  CalculationType: "Binned"

Binned:
  FileName: "./Inputs/ExampleAtmosphericBinning.root"
  EnergyAxisHistName: "EnergyAxisBinning"
  CosineZAxisHistName: "CosineZAxisBinning"

OscProbCalcer:
  - Implementation: "CUDAProb3Linear"
  - Config: "./build/Linux/Configs/OscProbCalcerConfigs/CUDAProb3Linear.yaml"
