General:
  Verbosity: "NONE"
  CosineZIgnored: false
  CalculationType: "Binned"

OscProbCalcer:
  - Config: "CUDAProb3:/exp/uboone/app/users/barrow/NuOscillator/build/Linux/Configs/OscProbCalcerConfigs/CUDAProb3.yaml"

Binned:
  FileName: "./Inputs/ExampleAtmosphericBinning.root"
  EnergyAxisHistName: "EnergyAxisBinning"
  CosineZAxisHistName: "CosineZAxisBinning"
