General:
  Verbosity: "NONE"
  CosineZIgnored: false
  CalculationType: "Binned"

Binned:
  FileName: "./Inputs/ExampleAtmosphericBinning.root"
  EnergyAxisHistName: "EnergyAxisBinning"
  CosineZAxisHistName: "CosineZAxisBinning"

OscProbCalcerSetup:
  ImplementationName: "CUDAProb3"
  OscChannelMapping:
    - Entry: "Electron:Electron"
    - Entry: "Electron:Muon"
    - Entry: "Electron:Tau"
    - Entry: "Muon:Electron"
    - Entry: "Muon:Muon"
    - Entry: "Muon:Tau"
    - Entry: "Tau:Electron"
    - Entry: "Tau:Muon"
    - Entry: "Tau:Tau"
