General:
  Verbosity: "NONE"
  CosineZIgnored: true
  CalculationType: "Binned"

OscProbCalcer:
  - Config: "CUDAProb3Linear:./build/Linux/Configs/OscProbCalcerConfigs/CUDAProb3Linear.yaml"

Binned:
  FileName: "./Inputs/ExampleAtmosphericBinning.root"
  EnergyAxisHistName: "EnergyAxisBinning"
  CosineZAxisHistName: "CosineZAxisBinning"
