General:
  Verbosity: "NONE"
  CosineZIgnored: true
  CalculationType: "Binned"

OscProbCalcer:
  - Config: "ProbGPULinear:./build/Linux/configs/OscProbCalcerConfigs/ProbGPULinear.yaml"

Binned:
  FileName: "FileName.root"
  EnergyAxisHistName: "EnergyAxis"
  CosineZAxisHistName: "CosineZAxis"
