General:
  Verbosity: "NONE"
  CosineZIgnored: true
  CalculationType: "Binned"

Binned:
  FileName: "./Inputs/ExampleAtmosphericBinning.root"
  EnergyAxisHistName: "EnergyAxisBinning"
  CosineZAxisHistName: "CosineZAxisBinning"

OscProbCalcer:
  - Implementation: "ProbGPULinear"
  - Config: "./build/Linux/Configs/OscProbCalcerConfigs/ProbGPULinear.yaml"
