General:
  Verbosity: "NONE"
  CosineZIgnored: true
  CalculationType: "Binned"

OscProbCalcer:
  - Config: "CUDAProb3Linear:./build/Linux/configs/OscProbCalcerConfigs/CUDAProb3Linear.yaml"

Binned:
  FileName: "FileName.root"
  EnergyAxisHistName: "EnergyAxis"
  CosineZAxisHistName: "CosineZAxis"
