General:
  Verbosity: "INFO"
  CosineZIgnored: true
  CalculationType: "SubSampling"

SubSampling:
  FileName: "./Inputs/SubSamplingBinningTemplate.root"
  CoarseEnergyAxisHistName: "CoarseEnergy"
  CoarseCosineZAxisHistName: "CoarseCosZ"
  FineEnergyAxisHistName: "FineEnergy"
  FineCosineZAxisHistName: "FineCosZ"

OscProbCalcerSetup:
  ImplementationName: "NuFASTLinear"
  OscChannelMapping:
    - Entry: "Electron:Electron"
    - Entry: "Electron:Muon"
    - Entry: "Electron:Tau"
    - Entry: "Muon:Electron"
    - Entry: "Muon:Muon"
    - Entry: "Muon:Tau"
    - Entry: "Tau:Electron"
    - Entry: "Tau:Muon"
    - Entry: "Tau:Tau"
