General:
  Verbosity: "NONE"
  CosineZIgnored: false
  CalculationType: "Unbinned"

OscProbCalcer:
  - Implementation: "CUDAProb3Linear"
  - Config: "./build/Linux/Configs/OscProbCalcerConfigs/CUDAProb3.yaml"
