General:
  Verbosity: "NONE"
  CosineZIgnored: true
  CalculationType: "Unbinned"

OscProbCalcer:
  - Implementation: "Prob3ppLinear"
  - Config: "./build/Linux/Configs/OscProbCalcerConfigs/Prob3ppLinear.yaml"
