General:
  Verbosity: "NONE"
  CosineZIgnored: true
  CalculationType: "Unbinned"

OscProbCalcer:
  - Implementation: "ProbGPULinear"
  - Config: "ProbGPULinear:./build/Linux/Configs/OscProbCalcerConfigs/ProbGPULinear.yaml"
