General:
  Verbosity: "NONE"
  CosineZIgnored: true
  CalculationType: "Unbinned"

OscProbCalcer:
  - Implementation: "CUDAProb3Linear"
  - Config: "./build/Linux/Configs/OscProbCalcerConfigs/CUDAProb3Linear.yaml"
