General:
  Verbosity: "INFO"
  CosineZIgnored: true
  CalculationType: "Unbinned"

OscProbCalcer:
  Implementation: "NuFASTLinear"
  Config: "./build/Linux/Configs/OscProbCalcerConfigs/NuFASTLinear.yaml"
