# Performs unit and integration testing

name: Validations CI

# The events that trigger the workflow
on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    name: ${{ matrix.name }}

    strategy:
      fail-fast: false  # Prevents cancellation of remaining jobs if one fails
      matrix:
        include:
          - name: DragRace_Atm_Binned
            cmake_options: -DUseCUDAProb3=1 -DUseOscProb=1
            exec: DragRace
            argument: 10 NuOscillatorConfigs/Binned_CUDAProb3.yaml NuOscillatorConfigs/Binned_OscProb.yaml
          - name: DragRace_Atm_Unbinned
            cmake_options: -DUseCUDAProb3=1 -DUseOscProb=1
            exec: DragRace	    
            argument: 10 NuOscillatorConfigs/Unbinned_CUDAProb3.yaml NuOscillatorConfigs/Unbinned_OscProb.yaml
          - name: DragRace_Beam_Binned
            cmake_options: -DUseCUDAProb3Linear=1 -DUseNuFASTLinear=1 -DUseProb3ppLinear=1
            exec: DragRace	    
            argument: 10 NuOscillatorConfigs/Binned_CUDAProb3Linear.yaml NuOscillatorConfigs/Binned_NuFASTLinear.yaml NuOscillatorConfigs/Binned_Prob3ppLinear.yaml
    container:
      image: ghcr.io/mach3-software/mach3:alma9latest

    steps:
    - uses: actions/checkout@v4


    - name: Get NuOscillator
      run: |
        cd /opt/
        git clone https://github.com/dbarrow257/NuOscillator.git NuOscillator
        cd NuOscillator
        git checkout ${{ github.head_ref }}
        mkdir build
        cd build
        cmake ../ -DUseGPU=0 -DUseMultithreading=1 -DUseDoubles=1 ${{ matrix.cmake_options }}

    - name: Build NuOscillator
      run: |
        cd /opt/NuOscillator/build
        make install # Build the project

    - name: Validations
      run: |
        source /opt/NuOscillator/build/Linux/bin/setup.NuOscillator.sh
        cd /opt/NuOscillator/
        build/Linux/bin//${{ matrix.exec }} ${{ matrix.argument }}
