# Performs unit and integration testing

name: Validations CI

# The events that trigger the workflow
on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    name: ${{ matrix.name }}

    strategy:
      fail-fast: false  # Prevents cancellation of remaining jobs if one fails
      matrix:
        include:
          - name: NuFASTLinear Comparison
            cmake_options: -DUseNuFASTLinear=1
            exec: SingleOscProbCalcer
            argument: NuOscillatorConfigs/OscProbCalcerConfigs/NuFASTLinear.yaml
            new_output: NuFASTLinear_New.txt
            old_output: NuFASTLinear_Stored.txt
          - name: OscProbLinear Comparison
            cmake_options: -DUseOscProb=1
            exec: SingleOscProbCalcer
            argument: NuOscillatorConfigs/OscProbCalcerConfigs/OscProbLinear.yaml
            new_output: OscProbLinear_New.txt
            old_output: OscProbLinear_Stored.txt	
          - name: Prob3ppLinear Comparison
            cmake_options: -DUseProb3ppLinear=1
            exec: SingleOscProbCalcer
            argument: NuOscillatorConfigs/OscProbCalcerConfigs/Prob3ppLinear.yaml
            new_output: Prob3ppLinear_New.txt
            old_output: Prob3ppLinear_Stored.txt	      

    container:
      image: ghcr.io/mach3-software/mach3:alma9latest

    steps:
    - uses: actions/checkout@v4

    - name: Get NuOscillator
      run: |
        cd /opt/
        git clone https://github.com/dbarrow257/NuOscillator.git NuOscillator
        cd NuOscillator
        git checkout ${{ github.head_ref }}
        mkdir build
        cd build
        cmake ../ -DUseGPU=0 -DUseMultithreading=1 -DUseDoubles=1 ${{ matrix.cmake_options }}

    - name: Build NuOscillator
      run: |
        cd /opt/NuOscillator/build
        make install # Build the project

    - name: Validations
      run: |
        source /opt/NuOscillator/build/Linux/bin/setup.NuOscillator.sh
        cd /opt/NuOscillator/
        build/Linux/bin//${{ matrix.exec }} ${{ matrix.argument }} | tee ${{ matrix.new_output }}

    - name: Check that the files are the exact same
      uses: LouisBrunner/diff-action@v2.0.0
      with:
        old: /opt/NuOscillator/.github/TestOutputs/${{ matrix.old_output }}
        new: /opt/NuOscillator/${{ matrix.new_output }}
        mode: strict
        tolerance: same