# This is a basic workflow make doxygen documentation every time develop is updated

name: Doxygen

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update

      - run: sudo apt-get install -y texlive

      - run: sudo apt-get install -y libjs-mathjax

      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: Docs/html
          config_file: ./Doxyfile

      - run: ls
      - run: ls Docs/html

